### ISSUE TITLE
效果怎么和原论文差这么多？

### ISSUE THREAD

**Issue by kilaOoO** [johnnylu305/Simple-does-it-weakly-supervised-instance-and-semantic-segmentation#2]

**Comment by johnnylu305** [comment]
In my opinion, I don't use M∩G+ to generate the labels for the network, so the result isn't great enough.

**Comment by kilaOoO** [comment]
我也觉得是这个原因，但主要差的有点多，因为在我看来差距可能不会这么大，所以才想咨询一下。

At 2019-07-18 21:10:29, "CHENG-YOU LU" <notifications@github.com> wrote:


In my opinion, I don't use M∩G+ to generate the labels for the network, so the result isn't great enough.

**Comment by johnnylu305** [comment]
Hello, @kilaOoO.
Yes, M∩G+ is the main reason why the performance is not good. However, there are several minor reasons. For example, they use early stopping and large batch sizes. Therefore, I can't follow all the parameters they gave because of the different structures.
